services:
  mariadb:
    build:
      context: ./srcs/requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    pull_policy: never
    env_file:
      - ./srcs/.env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./secrets:/run/secrets:ro
    networks:
      - inception
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -p\"$$MYSQL_ROOT_PASSWORD\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    build:
      context: ./srcs/requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    pull_policy: never
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - ./srcs/.env
    environment:
        WORDPRESS_DB_HOST: mariadb
        WORDPRESS_DB_PORT: 3306
    volumes:
      - wordpress_data:/var/www/html
      - ./secrets:/run/secrets:ro
    networks:
      - inception
    restart: unless-stopped

  nginx:
    build:
      context: ./srcs/requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    pull_policy: never
    depends_on:
      - wordpress
    env_file:
      - ./srcs/.env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./secrets:/run/secrets:ro
      - ./srcs/requirements/nginx/conf:/etc/nginx/conf.d:ro
    networks:
      - inception
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pzau/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pzau/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge